services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cis-320:latest
    container_name: cis-320-app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/cis320?sslmode=disable
      - REDIS_URL=redis://redis:6379/0
      - ALPACA_API=https://paper-api.alpaca.markets
    # Flags can be passed at runtime, e.g.:
    # docker compose run app --debug --dev
    volumes:
      - ./.env.local:/.env.local:ro
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: cis-320-redis
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: cis-320-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cis320
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./sql/trades.sql:/docker-entrypoint-initdb.d/010-trades.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cis320"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

volumes:
  redis-data: {}
  pg-data: {}
